version: '3.8'

services:
  postgres1:
    image: postgres:15
    container_name: postgres1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - ./backend/message_user.sql:/docker-entrypoint-initdb.d/message_user.sql:ro
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - postgres1
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:yourpassword@postgres1:5432/postgres"
    volumes:
      - ./backend:/app
    networks:
      - app_network

  react-app:
    build:
      context: ./chat-app  # Ensure this path matches your React app's folder
    container_name: react-app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local  # Ensures persistent storage for the PostgreSQL database

networks:
  app_network:
    driver: bridge  # Ensures all services can communicate over the same Docker network
