version: '3.1'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"  # Expose the backend FastAPI app on port 8000
    environment:
      DATABASE_URL: "postgresql://postgres:yourpassword@postgres1:5432/my_database"

    depends_on:
      - postgres1

  react-app:
    build:
      context: ./chat-app  # Ensure this path matches your React app's folder
    container_name: react-app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true


  postgres1:
    image: postgres
    container_name: postgres1
    restart: always
    environment:
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5435:5432"
    volumes:
      - ./backend/message_user.sql:/docker-entrypoint-initdb.d/message_user.sql


  postgres2:
    image: postgres
    container_name: postgres2
    restart: always
    environment:
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5434:5432"

