version: '3.1'

services:
  postgres1:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5433:5432"

  postgres2:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5434:5432"
